document.write(" appName : " + navigator.appName + "<br/>");
document.write("appCodeName : " + navigator.appCodeName + "<br/>");
document.write("platform : " + navigator.platform + "<br/>");
document.write("cookieEnabled : " + navigator.cookieEnabled + "<br/>");
document.write("product : " + navigator.product + "<br/>");
document.write("appVersion : " + navigator.appVersion + "<br/>");
document.write("userAgent : " + navigator.userAgent + "<br/>");
document.write("language : " + navigator.language + "<br/>");
document.write("onLine : " + navigator.onLine + "<br/>");
document.write("javaEnabled() : " + navigator.javaEnabled() + "<br/>");
